var json = {
	"peep1":{
		"fname":["First Name:","Andy"],
		"lname":["Last Name:","Bassiri"],
		"company":["Company:","Post Op Media"],
		"pnum":["Phone Number:","571-265-4221"],
		"email":["Email:","audioandy@gmail.com"],
		"addy":["Address:","19800 Mallard Pond Drive"],
		"bday":["Birthday:","2013-20-01"],
		"rock":["Rock:","Yes"],
		"paper":["Paper:","No"],
		"scissor":["Scissor:","Yes"],
		"donor":["Organ Donor:","Yes"],
		"soa":["Awesomeness:","6"],
		"cat":["Category:","Friend"],
		"quotes":["Best Quotes:","If my name was Press Firmly I would sound so manly"],
		"notes":["Notes:","Has a wonky eye"]
	},
	"peep2":{
		"fname":["First Name:","Meaghan"],
		"lname":["Last Name:","Bassiri"],
		"company":["Company:","FarWest"],
		"pnum":["Phone Number:","571-265-4221"],
		"email":["Email:","Meagers@gmail.com"],
		"addy":["Address:","19800 Mallard Pond Drive"],
		"bday":["Birthday:","2013-20-01"],
		"rock":["Rock:","Yes"],
		"paper":["Paper:","No"],
		"scissor":["Scissor:","No"],
		"donor":["Organ Donor:","No"],
		"soa":["Awesomeness:","6"],
		"cat":["Category:","Family"],
		"quotes":["Best Quotes:","Shut Up Andy."],
		"notes":["Notes:","Has a wonky leg"]
	},
	"peep3":{
		"fname":["First Name:","Danny"],
		"lname":["Last Name:","McDanners"],
		"company":["Company:","IRA"],
		"pnum":["Phone Number:","571-265-4221"],
		"email":["Email:","dannymcdan@gmail.com"],
		"addy":["Address:","19800 Mallard Pond Drive"],
		"bday":["Birthday:","2013-20-01"],
		"rock":["Rock:","Yes"],
		"paper":["Paper:","No"],
		"scissor":["Scissor:","No"],
		"donor":["Organ Donor:","No"],
		"soa":["Awesomeness:","6"],
		"cat":["Category:","Co-Worker"],
		"quotes":["Best Quotes:","God Bless Ireland"],
		"notes":["Notes:","Is make believe"]
	}
}